/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SellerDto
 */
export interface SellerDto {
    /**
     * 
     * @type {number}
     * @memberof SellerDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof SellerDto
     */
    login?: string;
    /**
     * 
     * @type {string}
     * @memberof SellerDto
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof SellerDto
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof SellerDto
     */
    lastName?: string;
    /**
     * 
     * @type {number}
     * @memberof SellerDto
     */
    fund?: number;
}
